### ISSUE TITLE
Kindly update with instructions and to latest Pyrebase

### ISSUE THREAD

**Issue by lohriialo** [thisbejim/news#1]
Hi @thisbejim 

I find this project very interesting but doesn't have instructions on how to use.

I tried it out but db.sort_by_start is where it's giving an error, unable to launch flask hence.

Could you please update the project to the latest pyrebase with a few lines on how to setup?

Thanks

**Comment by thisbejim** [comment]
Hi @lohriialo, yeah this project is waaaay outdated and was just something I threw together for fun (it isn't meant to be an example for people to follow). Your best bet is checking out the Pyrebase docs and playing around with Pyrebase in your own projects. 

Thanks for dropping by!
